import java.io.*;
import java.net.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;

public class HeadNTail {

	public void putHead( PrintWriter out ) {

		out.println("<META NAME=\"DATE_PUBLISHED\" CONTENT=\"Wed May 30 08:18:56 MDT 2001\">");
		out.println("<META NAME=\"TEMPLATE_VERSION\" CONTENT=\"v2.0\">");
		out.println("<META NAME=\"TEMPLATE_BUILD_DATE\" CONTENT=\"Wed Sep 27 08:30:30 MDT 2000\">");
		out.println("<META NAME=\"URL\" CONTENT=\"http://envy.central:8095/query.html\">");
		out.println("<META NAME=\"LAST_MODIFIED\" CONTENT=\"May 31, 2001 6:29:16 PM MST\">");
		out.println("<META NAME=\"LAST_MODIFIED_TEXT\" CONTENT=\"anna-karinb\">");
		out.println("<TITLE>SIT-LAB Inventory</TITLE>");
		out.println("  <META NAME=\"OWNER\" CONTENT=\"mark.hotchkiss@central.Sun.COM\">");
		out.println("  <META NAME=\"DESCRIPTION\" CONTENT=\"SIT-LAB\">");
		out.println("  <META NAME=\"KEYWORDS\" CONTENT=\"Security IT, inventory, query, authentication\">");
		out.println("  <META NAME=\"SECURITY\" CONTENT=\"Sun Confidential - For Internal Use Only\">");
		out.println("  <LINK REV=\"MADE\" HREF=\"mark.hotchkiss@Central.Sun.COM\">");
		out.println("<!-- NOINDEX -->");
		out.println("<STYLE TYPE=\"text/css\">");
		out.println("BODY { font-size: 12pt; font-family: helvetica, lucida sans; font-variant: normal; font-style: normal; background-color: #FFFFFF; color: #000000; }");
		out.println(".localheader { font-family: helvetica, lucida sans; font-size: 11pt; text-decoration: none; color: #FFFFFF; font-weight: bold; }");
		out.println(".locallinkhl { font-family:  helvetica, lucida sans; font-size: 11pt; text-decoration: none; color: #FFFFCC; font-weight: normal; }");
		out.println(".locallink { font-family: helvetica, lucida sans; font-size: 11pt; text-decoration: none; color: #FFFFFF; font-weight: normal; }");
		out.println(".locallinkt { font-family: helvetica, lucida sans; font-size: 14pt; text-decoration: none; color: #FFFFFF; font-weight: bold; }");
		out.println(".localsublink { font-family: helvetica, lucida sans; font-size: 10pt; text-decoration: none; color: #FFFFFF; font-weight: normal; }");
		out.println(".categorylink { font-family: helvetica, lucida sans; font-size: 11pt; text-decoration: none; color: #FFFFFF; font-weight: bold; }");
		out.println(".subcategorylink { font-family: helvetica, lucida sans; font-size: 8pt; text-decoration: none; color: #FFFFFF; font-weight: normal; }");
		out.println(".sunweb { font-family: helvetica, lucida sans; font-size: 12pt; text-decoration: none; color: #666699; font-weight: bold }");
		out.println(".sunwebLogo { font-family: helvetica, lucida sans; font-size: 18pt; text-decoration: none; color: #666699; font-weight: bold }");
		out.println(".breadcrumb { font-family: helvetica, lucida sans; font-size: 12pt; text-decoration: none; color: #FFFFFF; font-weight: bold; padding-top: 4; }");
		out.println(".sitelink { font-family: helvetica, lucida sans; font-size: 11pt; text-decoration: none; color: #000000; font-weight: normal; }");
		out.println("</STYLE>");
		out.println("<!-- INDEX -->");
		out.println("</HEAD>");
		out.println("<body BGCOLOR=\"#FFFFFF\" LINK=\"#666699\" VLINK=\"#9999CC\" ALINK=\"#FFFFFF\"  bgcolor=white>");
		out.println("<!-- NOINDEX -->");
		out.println("<!-- START PAGE HEADER -->");
		out.println("<!-- END PAGE HEADER -->");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\" WIDTH=\"100%\">");
		out.println("<TR>");
		out.println("<TD BGCOLOR=\"#666699\">");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"0\">");
		out.println("<TR>");
		out.println("<TD BGCOLOR=\"#FFFFCC\">");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"5\" WIDTH=\"172\">");
		out.println("<TR>");
		out.println("<TD>");
		out.println("<!-- START SUNWEB GLOBAL LINKS -->");
		out.println("<A HREF=\"http://sunweb.Central/\"><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>Home</B></FONT></A><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>&nbsp;&middot;&nbsp;</B></FONT>");
		out.println("<A HREF=\"http://sunweb.Central/search/\"><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>Search</B></FONT></A><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>&nbsp;&middot;&nbsp;</B></FONT>");
		out.println("<A HREF=\"http://sunweb.Central/a-z/\"><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>A&nbsp;to&nbsp;Z</B></FONT></A><!-- END SUNWEB GLOBAL LINKS -->");
		out.println("</TD>");
		out.println("</TR>");
		out.println("<TR>");
		out.println("<TD>");
		out.println("<!-- START SUNWEB LOGO LINK -->");
		out.println("<A HREF=\"http://sunweb.Central/\"><FONT CLASS=\"sunwebLogo\" SIZE=\"6\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>SunWeb</B></FONT></A><!-- END SUNWEB LOGO LINK -->");
		out.println("</TD>");
		out.println("</TR>");
		out.println("</TABLE>");
		out.println("</TD>");
		out.println("</TR>");
		out.println("</TABLE>");
		out.println("</TD>");
		out.println("<TD BGCOLOR=\"#666699\" VALIGN=\"TOP\" WIDTH=\"95%\">");
		out.println("<!-- START HEADER BAR -->");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\"><TR><TD>");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"5\">");
		out.println("<TR><TD NOWRAP>&nbsp;</TD></TR>");
		out.println("<TR><TD>&nbsp;<FONT FACE=\"helvetica, lucida sans\" SIZE=\"5\" COLOR=\"#FFFFFF\"><B>Inventory Database Tools</B></FONT></TD></TR>");
		out.println("</TABLE>");
		out.println("</TD></TR></TABLE>");
		out.println("<!-- END HEADER BAR -->");
		out.println("</TD>");
		out.println("</TR>");
		out.println("<TR>");
		out.println("<TD BGCOLOR=\"#666699\" VALIGN=\"TOP\" WIDTH=\"160\">");
		out.println("<BR>");
		out.println("<!-- START SEARCH FIELD -->");
		out.println("<FORM ACTION=\"http://sunsearch.central/query.html\">");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"1\" ALIGN=\"CENTER\" WIDTH=\"160\">");
		out.println("<TR><TD COLSPAN=\"2\" VALIGN=\"TOP\"><FONT FACE=\"helvetica, lucida sans\" SIZE=\"3\" COLOR=\"#FFFFFF\">Search SunWeb</FONT></TD></TR>");
		out.println("<TR><TD><INPUT TYPE=\"TEXT\" SIZE=\"12\" NAME=\"qt\"></TD>");
		out.println("<TD><FONT SIZE=\"3\" COLOR=\"#FFFFFF\" FACE=\"helvetica, lucida sans\"><INPUT TYPE=\"SUBMIT\" NAME=\"GO\" VALUE=\"GO\"></FONT></TD></TR>");
		out.println("<TR><TD COLSPAN=\"2\"><A HREF=\"http://sunsearch.Central/query.html?col=amer+emea+pacrim&qp=&qs=&qc=&pw=100%25&ws=1&ql=a&nh=25&lk=1&rf=0\"><FONT CLASS=\"locallink\" COLOR=\"#FFFFFF\" SIZE=\"-1\">Advanced Search</FONT></A></TD></TR>");
		out.println("</TABLE>");
		out.println("</FORM>");
		out.println("<!-- END SEARCH FIELD -->");
		out.println("<!-- START SIDEBAR NAVIGATION -->");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\" ALIGN=\"CENTER\" WIDTH=\"160\">");
		out.println("<TR><TD ALIGN=\"LEFT\" VALIGN=\"TOP\" COLSPAN=\"10\"><HR></TD></TR>");
		out.println("<TR><TD ALIGN=\"LEFT\" VALIGN=\"TOP\" COLSPAN=\"10\"><A HREF=\"./Login\"><FONT CLASS=\"locallink\" COLOR=\"#FFFFFF\">Home</FONT></A><BR></TD></TR>");
		out.println("<TR><TD ALIGN=\"LEFT\" VALIGN=\"TOP\" COLSPAN=\"10\"><HR></TD></TR>");
		out.println("<TR>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("<TD WIDTH=\"10%\">&nbsp;</TD>");
		out.println("</TR></TABLE>");
		out.println("<!-- END SIDEBAR NAVIGATION -->");
		out.println("</TD>");
		out.println("<TD VALIGN=\"TOP\" WIDTH=\"95%\">");
		out.println("<!-- START PAGE CONTENT TABLE -->");
		out.println("<TABLE WIDTH=\"100%\" BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"10\">");
		out.println("<TR>");
		out.println("<TD VALIGN=\"TOP\">");
		out.println("<!-- START PAGE CONTENT -->");
	}


	public void putTail( PrintWriter out ) {

		out.println("<a href= \"./Login\"> Home </a>");
		out.println("<p>");
		out.println("<!-- END PAGE CONTENT -->");
		out.println("</TD>");
		out.println("</TR>");
		out.println("</TABLE>");
		out.println("<!-- END PAGE CONTENT TABLE -->");
		out.println("</TD>");
		out.println("</TR>");
		out.println("<TR>");
		out.println("<TD BGCOLOR=\"#666699\" VALIGN=\"BOTTOM\">");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"1\" CELLPADDING=\"0\">");
		out.println("<TR>");
		out.println("<TD BGCOLOR=\"#FFFFCC\">");
		out.println("<TABLE BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"5\" WIDTH=\"172\">");
		out.println("<TR>");
		out.println("<TD>");
		out.println("<!-- START SUNWEB GLOBAL LINKS -->");
		out.println("<A HREF=\"http://sunweb.Central/\"><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>Home</B></FONT></A><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>&nbsp;&middot;&nbsp;</B></FONT>");
		out.println("<A HREF=\"http://sunweb.Central/search/\"><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>Search</B></FONT></A><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>&nbsp;&middot;&nbsp;</B></FONT>");
		out.println("<A HREF=\"http://sunweb.Central/a-z/\"><FONT CLASS=\"sunweb\" SIZE=\"2\" COLOR=\"#666699\" FACE=\"helvetica, lucida sans\"><B>A&nbsp;to&nbsp;Z</B></FONT></A><!-- END SUNWEB GLOBAL LINKS -->");
		out.println("</TD>");
		out.println("</TR>");
		out.println("</TABLE>");
		out.println("</TD>");
		out.println("</TR>");
		out.println("</TABLE>");
		out.println("</TD>");
		out.println("<TD VALIGN=\"BOTTOM\">");
		out.println("</TD>");
		out.println("</TR>");
		out.println("</TABLE>");
		out.println("<!-- START PAGE FOOTER -->");
		out.println("<BR>");
		out.println("<FONT FACE=\"helvetica, lucida sans\">[ <A HREF=\"http://webhome.corp/security/info_protection/intro.html\">Sun Proprietary/Confidential</A>: Internal Use Only ]&nbsp;&nbsp;&nbsp;&nbsp; [ Feedback to <A HREF=mailto:mark.hotchkiss@Sun.COM>Mark Hotchkiss</A> ]</FONT>");
		out.println("<!-- END PAGE FOOTER -->");
		out.println("<!-- INDEX -->");
		out.println("</body>");
		out.println("</html>");
		out.flush();
	}
}
