package com.studytrails.tutorials.springmethodinjection;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class TestMethodInjection {

	public static void main(String[] args) {
		System.out.println("************** BEGINNING PROGRAM **************");

		ApplicationContext context = new ClassPathXmlApplicationContext(
				"spring-config.xml");

		TicketVendingMachine ticketVendingMachine = (TicketVendingMachine) context
				.getBean("ticketVendingMachine");
		Ticket ticket = ticketVendingMachine.generateTicket();
		System.out
				.println("The ticket successfully generated by ticket vending machine = "
						+ ticket);

		System.out.println("************** ENDING PROGRAM **************");
	}
}