---
- name: install apache & php & mysql
  hosts: mrh-group
  gather_facts: true
  tasks:
    - name: "install apache2"
      package: name=apache2 state=present
    - name: "install apache2-php5"
      package: name=libapache2-mod-php state=present
    - name: "install php-cli"
      package: name=php-cli state=present
    - name: "install php-gd"
      package: name=php-gd state=present
    - name: "install php-mysql"
      package: name=php-mysql state=present