# .bash_profile runs first by default
# put "source ~/.bashrc" in .bash_profile so that this file gets read
set -o vi

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH

export PYTHONPATH=$PYTHONPATH:/Users/mhotchkiss/asgard/util/src/python
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH="$PATH:$HOME/.rvm/bin:." # Add RVM to PATH for scripting
export CONFIG_PATH=/Users/mhotchkiss/asgard/util/src/python/config/app.cfg
export DATA_PATH=/Users/mhotchkiss/asgard/util/src/python/test/data/test_data.yaml
export TEST_ENV=qa1

export SIREN_KEY_PASSWORD='...'
export DEV_COUCHDB_PASSWORD='...'
export DEV_EGO_DB_PASSWORD='...'
export DEV_LS_DB_PASSWORD='...'
export DEV_RSA_PASSWORD='...'
export DEV_RABBITMQ_PASSWORD='...'
export QA1_COUCHDB_PASSWORD='...'
export QA1_EGO_DB_PASSWORD='...'
export QA1_RABBITMQ_PASSWORD='...'
export QA2_COUCHDB_PASSWORD='...'
export QA2_EGO_DB_PASSWORD='...'
export QA2_RABBITMQ_PASSWORD='...'
export QA3_COUCHDB_PASSWORD='...'
export QA3_EGO_DB_PASSWORD='...'
export QA3_RABBITMQ_PASSWORD='...'
export QA4_COUCHDB_PASSWORD='...'
export QA4_EGO_DB_PASSWORD='...'
export QA4_RABBITMQ_PASSWORD='...'
export QA5_COUCHDB_PASSWORD='...'
export QA5_EGO_DB_PASSWORD='...'
export QA5_RABBITMQ_PASSWORD='...'
export STG_LS_DB_PASSWORD='...'
export STG_RSA_PASSWORD='...'
